version: '3.7'

networks:
    default:
        driver: bridge

volumes:
    mysql-data:
        name: ${APP_NAME}__mysql-db

services:
    fav-nginx:
        image: nginx:mainline-alpine
        volumes:
            - ${PROJECT_PATH}:/srv/app
            - ${PROJECT_PATH}/docker-local/nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf
            - ${PROJECT_PATH}/docker-local/nginx/certs/favvertgroup.ru.crt:/etc/nginx/favvertgroup.ru.crt
            - ${PROJECT_PATH}/docker-local/nginx/certs/favvertgroup.ru.key:/etc/nginx/favvertgroup.ru.key
        depends_on:
            - fav-app
            - fav-mysql
        links:
            - fav-app
        restart: unless-stopped
        ports:
            - "8090:80"
            - "8091:443"
        networks:
            default:

    fav-app:
        build:
            context: ./docker-local/php-fpm
            args:
                - USER={USER}
                - USER_ID={USER_ID}
        volumes:
            - ${PROJECT_PATH}:/srv/app
        depends_on:
            - fav-mysql
        links:
            - fav-mysql
        networks:
            default:
        # labels:
        #     traefik.enable: false
        #     deck-chores.schedule-run-minute.command: php artisan schedule:run
        #     deck-chores.schedule-run-minute.interval: 1 minute

    fav-mysql:
        image: mysql:8
        restart: unless-stopped
        ports:
            - "33061:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: secret_root_password
        volumes:
            - mysql-data:/var/lib/mysql/
        networks:
            default:
        # labels:
        #     traefik.enable: false
