version: '3.7'

networks:
    default:
        driver: bridge
    traefik-net:
        name: traefik_net
        external: true

volumes:
    mysql-data:
        name: ${APP_NAME}__mysql-db

services:
    nginx:
        image: nginx:mainline-alpine
        volumes:
            - ${PROJECT_PATH}:/srv/app
            - ${PROJECT_PATH}/docker-local/nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        links:
            - app
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${APP_NAME}-nginx.rule=Host(`${PROJECT_LOCAL_HOSTNAME}`)"
            - "traefik.http.routers.${APP_NAME}-nginx.entrypoints=web"
            - "traefik.docker.network=traefik_net"
        networks:
            default:
            traefik-net:

    app:
        build:
            context: ./docker-local/php-fpm
            args:
                - USER={USER}
                - USER_ID={USER_ID}
        volumes:
            - ${PROJECT_PATH}:/srv/app
        depends_on:
            - mysql
        links:
            - mysql
        networks:
            default:
            traefik-net:
        labels:
            traefik.enable: false
            deck-chores.schedule-run-minute.command: php artisan schedule:run
            deck-chores.schedule-run-minute.interval: 1 minute

    mysql:
        image: mysql:8
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: secret_root_password
        volumes:
            - mysql-data:/var/lib/mysql/
        networks:
            default:
        labels:
            traefik.enable: false
